console.log(34 + 71)
console.log(123 - 67)
console.log(56 * 23)
console.log(45 / 5)
console.log(5 ** 7)
console.log(33 % 6)
console.log("Jason".length)
console.log("Jason".includes("e"))
console.log("Jason".charAt(0))
console.log("Jason".toUpperCase())