console.log(34 + 71)
console.log(123 - 67)
console.log(56 * 23)
console.log(45 / 5)
console.log(5 ** 7)
console.log(33 % 6)
console.log("Jason".length)
console.log("Jason".includes("e"))
console.log("Jason".charAt(0))
console.log("Jason".toUpperCase())
console.log(34 / 3 > 67 / 2)
console.log(5 == "5")
console.log(5 === "5")
console.log(!3 === 3)
console.log("LEARN".length === 5 && "Student".length === 7)
console.log("LEARN".length === 5 || "Student".length === 10)
console.log("LEARN".includes("RN"))
console.log("LEARN".includes("rn"))
console.log("LEARN"[0] === "l")
console.log("LEARN"[0] === "L")

var theQuestion = "life, the universe, and everything";
var theAnswer = 42;

console.log(theAnswer / 2)
console.log(theQuestion.length)
console.log(theQuestion.indexOf("f"))
console.log(theQuestion + theAnswer)
console.log(theQuestion.slice(6, 18))
console.log(theQuestion.charAt(0))
console.log(theQuestion.length > theAnswer)